modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues"

[[mods]]
modId="enchdesc"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.enchdesc]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.enchdesc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="CLIENT"