modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues"

[[mods]]
modId="enchdesc"
updateJSONURL="https://updates.blamejared.com/get?n=enchantmentdescriptions&gv=1.16.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.enchdesc]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.enchdesc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.enchdesc]]
    modId="bookshelf"
    mandatory=true
    versionRange="[6.1,)"
    ordering="AFTER"
    side="CLIENT"